feat: t3 - find namespaces without the backup
krasninja/devops-camp-2023 pull request #3
Opened 2023-04-02 12:43 UTC by krasninja

- feat: Add files without extension script
- fix: improve files processing
- feat: Add unique directories script
- fix: Remove wrong commited files
- feat: Add namespaces compare script

2023-04-04 04:03 UTC, roman-mightydevops approved these changes

2023-04-04 09:15 UTC, kseniyashaydurova requested changes

2023-04-04 09:15 UTC, kseniyashaydurova commented on chapter2/tests/t3/chapter2-t3-velero-eks-diff.sh
> +readonly VELERO_CONFIG='https://gist.githubusercontent.com/dmitry-mightydevops/016139747b6cefdc94160607f95ede74/raw/030a82af2489bc353cec370779cfd06852668e29/velero.yaml'
1. Let's please add nice output when files not found, because for example if Dmitry will remove these files, your script will stop working correctly and it won't show any nice and clear error. This is the case when both files absent.
![image](https://user-images.githubusercontent.com/26448672/229732072-37dd96c0-0feb-4c02-91b5-23ce89eadca9.png)

2. Also if no `velero.yaml` configuration was loaded your script just prints all namespaces from the 2d file and even doesn't say anything, like `velero.yaml` file doesn't exist. That is not user friendly and will make people guess why out output is not the one it should be.

2023-04-04 09:15 UTC, kseniyashaydurova commented on chapter2/tests/t3/chapter2-t3-velero-eks-diff.sh
> +  | sed 's/\([[:alnum:]]*\)/- \1/'
You can simplify `sed` to just this, it will look easier to read and understand:
```
sed 's/^/- /'
```

2023-04-04 12:00 UTC, krasninja commented on chapter2/tests/t3/chapter2-t3-velero-eks-diff.sh
> +readonly VELERO_CONFIG='https://gist.githubusercontent.com/dmitry-mightydevops/016139747b6cefdc94160607f95ede74/raw/030a82af2489bc353cec370779cfd06852668e29/velero.yaml'
1,2 - Add method to chech if files exist

2023-04-07 10:56 UTC, kseniyashaydurova approved these changes

2023-07-07 05:00 UTC, merged